### ISSUE TITLE
b._options is undefined

### ISSUE THREAD

**Issue by dfcreative** [goto-bus-stop/browser-pack-flat#24]
I am trying to run plugin as `browserify` package transform and get

```sh
C:\projects\regl-scatter2d\node_modules\browser-pack-flat\plugin.js:6
    debug: opts.debug || b._options.debug,
                                   ^

TypeError: Cannot read property 'debug' of undefined
    at apply (C:\projects\regl-scatter2d\node_modules\browser-pack-flat\plugin.js:6:36)
    at nr (C:\projects\regl-scatter2d\node_modules\module-deps\index.js:301:23)
    at C:\projects\regl-scatter2d\node_modules\resolve\lib\async.js:45:21
    at onfile (C:\projects\regl-scatter2d\node_modules\resolve\lib\async.js:190:27)
    at onex (C:\projects\regl-scatter2d\node_modules\resolve\lib\async.js:104:32)
    at C:\projects\regl-scatter2d\node_modules\resolve\lib\async.js:24:24
```

It should not be difficult to fix I guess?

**Comment by goto-bus-stop** [comment]
`b._options` should always be defined when browser-pack-flat is used as a plugin. it's more helpful if the plugin throws when it's used incorrectly tho, so b67edd4 :D
